sudo: required
dist: trusty
language: ruby
cache:
  bundler: true
rvm:
  - 2.6.5
env:
  global:
    - BUNDLE_JOBS=4
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
    - JAVA_OPTS=-Djava.security.egd=file:/dev/urandom
addons:
  postgresql: '9.4'
  apt:
    sources:
      - ubuntu-sdk-team
    packages:
      - libqt5webkit5-dev
      - qtdeclarative5-dev
before_install:
  - gem install bundler
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cp config/secrets.yml.travis config/secrets.yml
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script: bundle exec rspec spec
