version: '3.4'
services:
  ruby:
    build:
      context: .
      dockerfile: Dockerfile.passenger
    ports:
      - 80:80
      - "3000:3000"
      - "443:443"
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      AUTH_SERVER_ID: ${AUTH_SERVER_ID}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      HOST_NAME: ${HOST_NAME}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      PASSENGER_APP_ENV: ${PASSENGER_APP_ENV}
      ILLIAD_PASSWORD: ${ILLIAD_PASSWORD}
      SOLR_HOST: ${SOLR_HOST}
      SOLR_PORT: ${SOLR_PORT}
      OAUTHTOKEN: ${OAUTHTOKEN}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
  solr:
    build:
      context: .
      dockerfile: Dockerfile.solr
    ports:
     - "8983:8983"
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
     - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    ports:
     - "5672:5672"
     - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "annex-ims"
      RABBITMQ_DEFAULT_VHOST: "annex-ims"



