production:
  solr:
    hostname: localhost
    port: 8080
    log_level: WARNING
    # path: /solr/production
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    # path: /solr/development

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    # path: /solr/test
    
staging:
  solr:
    url: http://localhost:8080/solr/annex_ims
    # hostname: localhost
    # port: 8080
    log_level: WARNING
    # path: /solr/annex_ims
    read_timeout: 2
    open_timeout: 0.5
