production:
  solr:
    hostname: {{ solr_host }}
    port: 8983
    log_level: WARNING
    path: /solr/annex-ims
    timeout: 2
    open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8983
    path: /solr/annex-ims
    log_level: WARNING
    timeout: 2
    open_timeout: 0.5

test:
  solr:
    hostname: localhost
    port: 8983
    path: /solr/annex-ims
    log_level: WARNING
