---
chdir: "./"
environment: development
address: 127.0.0.1
port: 3021
timeout: 30
log: log/thin.log
pid: tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
threadpool_size: 20
daemonize: true
ssl: true
ssl_key_file: ./config/localhost.key
ssl_cert_file: ./config/localhost.crt
ssl_disable_verify: true
